turbojpeg: fix EXTERN macro definition conflict
EXTERN macro definition conflict causes build break:

```bash
In file included from libjpeg-turbo/libjpeg-turbo/turbojpeg.c:47:
libjpeg-turbo/libjpeg-turbo/transupp.h:179:1: warning: return type defaults to 'int' [-Wimplicit-int]
  179 | EXTERN(boolean) jtransform_parse_crop_spec(jpeg_transform_info *info,
      | ^~~~~~
libjpeg-turbo/libjpeg-turbo/transupp.h: In function 'EXTERN':
libjpeg-turbo/libjpeg-turbo/transupp.h:179:17: error: expected declaration specifiers before 'jtransform_parse_crop_spec'
  179 | EXTERN(boolean) jtransform_parse_crop_spec(jpeg_transform_info *info,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

Put setjmp.h at the top of the include to bypass the
EXTERN macro definition conflict problem in nuttx's setjmp.h.

Signed-off-by: pengyiqiang <pengyiqiang@xiaomi.com>